[tool.poetry]
name = "pyloid"
version = "0.17.4"
description = ""
authors = ["aesthetics-of-record <111675679+aesthetics-of-record@users.noreply.github.com>"]
readme = "README.md"
packages = [
    { include = "pyloid", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
pyside6 = "^6.8.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
